schema:
- name: realize
  path: .
  commands:
    fmt:
      status: true
    generate:
      status: true
    vet:
      status: true
    test: 
      status: true
    build:
      status: true
    install:
      status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    - mod
    ignored_paths:
    - .git
